
platform :ios, '13.0'

target 'Flash Chat iOS13' do

  
  post_install do |pi|
  pi.pods_project.targets.each do |t|
  t.build_configurations.each do |config|
  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
     end
   end
  end

  # Pods for Flash Chat iOS13
    pod 'FirebaseAuth', :modular_headers => true
    pod 'FirebaseFirestore', :modular_headers => true
    pod 'GoogleUtilities', :modular_headers => true
    pod 'FirebaseCore', :modular_headers => true

end
